export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';
export const CATEGORY_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORY_FAIL = 'CATEGORY_FAIL';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORY = 'GET_CATEGORY';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';
export const FILTERED_PRODUCTS = 'FILTERED_PRODUCTS';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_SINGLE_PRODUCT = 'GET_SINGLE_PRODUCT';
export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const REMOVE_CART = 'REMOVE_CART';

export const CREATE_ORDER = 'CREATE_ORDER';
export const LIST_ORDERS = 'LIST_ORDERS';

export const UPDATE_USER = 'UPDATE_USER';

export const RESET_CART = 'RESET_CART';
export const CAROUSEL_PRODUCTS = 'CAROUSEL_PRODUCTS';
export const SOLD_PRODUCTS = 'SOLD_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const ADD_MAIL_NEWSLETTER = 'ADD_MAIL_NEWSLETTER';
